name: cicd_demo_128
    
on:
  push:
    branches:
      - main
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
 
  test:
    environment: PROD1
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test 
        run: echo Run PROD deployment.      

  deploy:
    environment: PROD
    needs: test
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deployment 
        run: echo Run PROD deployment.
